### ISSUE TITLE
ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by SamGreenwood84** [SamGreenwood84/11-to-do-list#1]
at file:///C:/Users/sam/Bootcamp/challenges/11-to-do-list/routes/htmlRoutes.js:5:28
    at Layer.handle [as handle_request] (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\index.js:175:3)
    at router (C:\Users\sam\Bootcamp\challenges\11-to-do-list\node_modules\express\lib\router\index.js:47:12)

import express from "express";
const app = express();
const PORT = process.env.PORT || 3000;
import htmlRoutes from "./routes/htmlRoutes.js";

//Middleware
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(express.static("public"))
app.use("/", htmlRoutes)

app.listen(PORT, () => {
  console.log(`Server running on ${PORT}`);
})

**Comment by SamGreenwood84** [comment]
import express from "express"
import path from "path"
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url); // get the resolved path to the file
const __dirname = path.dirname(__filename); // get the name of the directory
console.log(__dirname);

const router = express.Router()
router.get("/notes", (req, res) => {
    res.sendFile(path.join(__dirname, '../public/notes.html'));
});
export default router;

**Comment by SamGreenwood84** [comment]
Referenced from: Ntsika Silvano @nsilvano ask-300573 Learning Assistant sent me to:
https://iamwebwiz.medium.com/how-to-fix-dirname-is-not-defined-in-es-module-scope-34d94a86694d
adjusted my own code to work
